### ISSUE TITLE
Ubuntu 22.4 & conda

### ISSUE THREAD

**Issue by mmann1123** [jgrss/geowombat#224]
I was just mucking around with docker and testing the latest ubuntu version 22.4,  and conda install. 

I got the following errors on testing. Sops is installed, so not sure what's going on here.

I am wondering if it has to do more with conda install rather than the new ubuntu version 

```
======================================================================
ERROR: test_coreg_data (test_coreg.TestCOREG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/geowombat/tests/test_coreg.py", line 29, in test_coreg_data
    data = gw.coregister(
  File "/root/miniconda3/lib/python3.9/site-packages/geowombat/core/sops.py", line 1242, in coregister
    raise NameError
NameError

======================================================================
ERROR: test_coreg_shift (test_coreg.TestCOREG)
Tests a 1-pixel shift.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/geowombat/tests/test_coreg.py", line 79, in test_coreg_shift
    shifted = gw.coregister(
  File "/root/miniconda3/lib/python3.9/site-packages/geowombat/core/sops.py", line 1242, in coregister
    raise NameError
NameError

======================================================================
ERROR: test_coreg_transform_data (test_coreg.TestCOREG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/geowombat/tests/test_coreg.py", line 50, in test_coreg_transform_data
    data = gw.coregister(
  File "/root/miniconda3/lib/python3.9/site-packages/geowombat/core/sops.py", line 1242, in coregister
    raise NameError
NameError

======================================================================
ERROR: test_array_type (test_properties.TestProperties)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/geowombat/tests/test_properties.py", line 36, in test_array_type
    self.assertTrue(src.gw.array_is_dask)
AttributeError: 'GeoWombatAccessor' object has no attribute 'array_is_dask'

======================================================================
ERROR: test_chunksize_check (test_properties.TestProperties)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/geowombat/tests/test_properties.py", line 42, in test_chunksize_check
    self.assertEqual(src.gw.check_chunksize(64, 128), 64)
AttributeError: 'GeoWombatAccessor' object has no attribute 'check_chunksize'

----------------------------------------------------------------------
```

**Comment by jgrss** [comment]
Those properties were added in recent versions and would have failed tests. So `conda` must not be installing the most recent build?

**Comment by mmann1123** [comment]
Yeah that's what I figured. I'll take a look. Conda-forge seems to be
having a longer lag recently.

**Comment by mmann1123** [comment]
This is resolved...
