### ISSUE TITLE
Stac import

### ISSUE THREAD

**Issue by mmann1123** [jgrss/geowombat#287]
I am getting an error when importing open_stac
@jgrss 
``` python
from geowombat.core.stac import open_stac
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mmann1123/miniconda3/envs/test/lib/python3.10/site-packages/geowombat/core/stac.py", line 117, in <module>
    class _STACCatalogOpeners:
  File "/home/mmann1123/miniconda3/envs/test/lib/python3.10/site-packages/geowombat/core/stac.py", line 118, in _STACCatalogOpeners
    element84 = _Client.open
NameError: name '_Client' is not defined
```

**Comment by jgrss** [comment]
I cannot reproduce this off of `main`. Did you install the 'stac' extra? I created a new venv and installed locally via `pip install .[stac]`.

**Comment by mmann1123** [comment]
Yeah I did the conda forge stac install.  I will try pip, maybe I messed something up with the conda buid?
