### ISSUE TITLE
[BUG] retry package not listed as a requirement

### ISSUE THREAD

**Issue by rdenham** [jgrss/geowombat#77]
Seems like the 'retry' package is now needed for gw 1.7.3, but it isn't listed in requirements.txt.

```
❯ python
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import geowombat as gw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv38gdal33/lib/python3.8/site-packages/geowombat/__init__.py", line 2, in <module>
    from .core.api import open
  File ".venv38gdal33/lib/python3.8/site-packages/geowombat/core/api.py", line 18, in <module>
    from . import geoxarray
  File ".venv38gdal33/lib/python3.8/site-packages/geowombat/core/geoxarray.py", line 19, in <module>
    from ..util import imshow as gw_imshow
  File ".venv38gdal33/lib/python3.8/site-packages/geowombat/util/__init__.py", line 2, in <module>
    from .web import GeoDownloads
  File ".venv38gdal33/lib/python3.8/site-packages/geowombat/util/web.py", line 14, in <module>
    from ..radiometry import BRDF, LinearAdjustments, RadTransforms, landsat_pixel_angles, sentinel_pixel_angles, QAMasker, DOS, SixS
  File ".venv38gdal33/lib/python3.8/site-packages/geowombat/radiometry/__init__.py", line 4, in <module>
    from .sr import LinearAdjustments, RadTransforms, DOS
  File ".venv38gdal33/lib/python3.8/site-packages/geowombat/radiometry/sr.py", line 11, in <module>
    from .sixs import AOT, SixS
  File ".venv38gdal33/lib/python3.8/site-packages/geowombat/radiometry/sixs.py", line 20, in <module>
    from ..data import LUTDownloader, NASAEarthdataDownloader
  File ".venv38gdal33/lib/python3.8/site-packages/geowombat/data/__init__.py", line 7, in <module>
    from retry import retry
ModuleNotFoundError: No module named 'retry'
>>> exit()

Not a big issue, but is nice for installing if it is added as a requirement.

**Comment by jgrss** [comment]
Thanks -- added in [93847d8f4369037273dcf1ddce1853e20d99bc1b](https://github.com/jgrss/geowombat/commit/93847d8f4369037273dcf1ddce1853e20d99bc1b)
