### ISSUE TITLE
Cython & _moving Issue?

### ISSUE THREAD

**Issue by mmann1123** [jgrss/geowombat#90]
I am trying to build out a docker container to do development in (keep breaking my env by accident). 

Here is the compose file:

```

FROM ubuntu:20.04
USER root

RUN apt update -y && apt upgrade -y && \
    apt install -y software-properties-common && \
    add-apt-repository ppa:ubuntugis/ppa && \
    apt update -y && apt install -y \
    gdal-bin \
    geotiff-bin \
    git \
    libgdal-dev \
    libgl1 \
    libspatialindex-dev \ 
    wget \
    python-is-python3 \
    pip \
    g++ 

RUN pip install Cython numpy  

# RUN pip-compile requirements.txt
RUN git clone https://github.com/jgrss/geowombat.git
WORKDIR "/geowombat"
RUN pip install -r requirements.txt

RUN  python setup.py install  
RUN  pip install sklearn-xarray  pip-tools rtree ipykernel

# works but doesn't bind
RUN python -c "import geowombat as gw"
RUN python -c "import rasterio;from rasterio.crs import CRS; cc = CRS.from_epsg(4326)"

```

In the development environment I have always gotten the following error. I had been just commenting out the import, but that is stupid.  

Any idea what is going on? I think this is an cython issue, but not sure how to resolve it.  
 
```
Step 10/11 : RUN python -c "import geowombat as gw"
 ---> Running in 97cdbb6f6a2d
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/geowombat/geowombat/__init__.py", line 2, in <module>
    from .core.api import open
  File "/geowombat/geowombat/core/__init__.py", line 1, in <module>
    from ..backends import transform_crs
  File "/geowombat/geowombat/backends/__init__.py", line 2, in <module>
    from .xarray_ import concat, mosaic
  File "/geowombat/geowombat/backends/xarray_.py", line 7, in <module>
    from ..core.windows import get_window_offsets
  File "/geowombat/geowombat/core/windows.py", line 1, in <module>
    from .util import n_rows_cols
  File "/geowombat/geowombat/core/util.py", line 9, in <module>
    from ..moving import moving_window
  File "/geowombat/geowombat/moving/__init__.py", line 1, in <module>
    from ._moving import moving_window
ModuleNotFoundError: No module named 'geowombat.moving._moving'
The command '/bin/sh -c python -c "import geowombat as gw"' returned a non-zero code: 1
The terminal process "/usr/bin/bash '-c', 'docker build --pull --rm -f "docker_debug" -t dbug2 "."'" terminated with exit code: 1.
```

**Comment by mmann1123** [comment]
Resolved. Clearly had to run setup still. was thrown off by instructions

```
FROM ubuntu:20.04
# FROM python:3.7.13-buster  
USER root

RUN apt update -y && apt upgrade -y && \
    apt install -y software-properties-common && \
    add-apt-repository ppa:ubuntugis/ppa && \
    apt update -y && apt install -y \
    gdal-bin \
    geotiff-bin \
    git \
    libgdal-dev \
    libgl1 \
    libspatialindex-dev \ 
    wget \
    python-is-python3 \
    pip \
    g++ 

RUN pip install Cython numpy GDAL pip-tools rtree ipykernel

RUN echo ' cython>=0.29.0  \n\  
    dask[array,dataframe]>=2021.* \n\ 
    distributed>=2021.* \n\
    geopandas>=0.8.0          # via -r requirements.in \n\
    joblib>=0.16.0            # via -r requirements.in, scikit-learn \n\
    matplotlib>=3.3.0         # via -r requirements.in \n\
    numpy>=1.19.0             # via -r requirements.in, dask, matplotlib, pandas, rasterio, scikit-learn, scipy, snuggs, xarray \n\
    opencv-python \n\
    pandas>=1.*             # via -r requirements.in, dask, geopandas, xarray \n\
    pyproj>=2.6.0             # via -r requirements.in, geopandas \n\
    rasterio>=1.2.0,<=1.2.6 \n\
    retry \n\
    requests \n\
    scikit-learn>=0.23.0      # via -r requirements.in \n\
    scipy>=1.5.0              # via -r requirements.in, scikit-learn \n\
    shapely>=1.7.0            # via -r requirements.in, geopandas \n\
    tqdm>=4.62.0              # via -r requirements.in \n\
    xarray>=0.17.0            # via -r requirements.in \n\
    cryptography ' > requirements.txt 

RUN pip install -r requirements.txt

RUN git clone https://github.com/jgrss/geowombat.git
RUN cd geowombat \ 
    pip install -r geowombat/requirements.txt \ 
    python3 setup.py install

RUN python -c "import geowombat as gw"
RUN python -c "import rasterio;from rasterio.crs import CRS; cc = CRS.from_epsg(4326)"
```

**Comment by mmann1123** [comment]
Ok I guess I don't understand why but when you import geowombat from the outer most directory, it doesn't throw any errors with `_moving`.  I am assuming it has to do with the location of the cythonized files, but not sure.
